name: Update html text with github variable value

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # generic github step
      - name: Use latest push to current branch 
        uses: actions/checkout@v2

      # replaces {{test}} in index.html with value of secrets.TEST in gihub repo
      - name: Replace script text with github variable value
        run: |
          sed -i 's/{{BEARERAUTH}}/'"${{ secrets.BEARERAUTH }}"'/g' scripts.js
      
      - name: Replace script text with github variable value2
        run: |
          sed -i 's/{{POSTAPI}}/'"${{ secrets.POSTAPI }}"'/g' scripts.js

      # generic github step
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
